# file: .github/workflows/show-directory.yml
name: show-directory

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup and test
        run: |
          make setup
          make test
          make lint

      