# file: .github/workflows/show-directory.yml
name: show-directory

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup
        run: make setup
      
      - name: Start server and run tests
        run: |
          # Запускаем сервер в фоновом режиме
          make start &
          # Ждем немного пока сервер запустится
          sleep 10
          # Запускаем тесты
          make test
          make lint